---
title: "Flexdashboard"
author: "Mehana Leafchild"
date: "11/18/24"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
    theme:
      bootswatch: yeti
      navbar: 
        - { title: "Mehana", href: "https://mehana-l.github.io", align: right }
        - { text: "fa fa-GitHub", icon: "fa-github", href: "https://mehana-l.github.com", align: right, target:
        blank }
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(knitr)
```

# Page 1
## Row 

### Summary

This is just some text to see what it looks like to have a text block. What information should I put here?

Here is a second line of text.

## Row

### Chart A

TEST

```{r}
ggplot(diamonds, aes(x = carat, y = price)) +
  geom_point(alpha=0.1, size=1)
```

### Chart B

```{r}
diamonds %>%
  mutate(color = fct_rev(color)) %>% 
  ggplot(aes(x = color, y = price, color = color)) +
  geom_boxplot()
```

## Row {.tabset .tabset-fade data-height="400"}

### Chart C

```{r}
starwars_data <- starwars %>%
  
knitr::kable(starwars)
```

### Chart D

This is some test text

```{r}
test <- ggplot(diamonds, aes(x = price, y = after_stat(density))) + 
  geom_freqpoly(aes(color = cut), binwidth = 500, linewidth = 0.75)

ggplotly(test)
```

# Page 2

## Row

### Chart E

```{r}
knitr::kable(mpg)
```